function bankTrans(bankCode){
    var bank = {
    	"ICBC": {
    		"bankCode": "ICBC",
    		"bankId": "61",
    		"bankName": "中国工商银行",
    		"imgName": "gongshang",
            "bigImgName" : "gongs_bank",
            "smallIcon" : 'gongshang',
    	},
    	"ABC": {
    		"bankCode": "ABC",
    		"bankId": "62",
    		"bankName": "中国农业银行",
    		"imgName": "nongye",
            "bigImgName" : "nongy_bank",
            "smallIcon" : 'nongye',
    	},
    	"CCB": {
    		"bankCode": "CCB",
    		"bankId": "63",
    		"bankName": "中国建设银行",
    		"imgName": "jianshe",
            "bigImgName" : "jians_bank",
            "smallIcon" : 'jianshe',
    	},
    	"BOC": {
    		"bankCode": "BOC",
    		"bankId": "64",
    		"bankName": "中国银行",
    		"imgName": "zhongguo",
            "bigImgName" : "zhongg_bank",
            "smallIcon" : 'zhongguo',
    	},
    	"BOCOM": {
    		"bankCode": "BOCOM",
    		"bankId": "65",
    		"bankName": "中国交通银行",
    		"imgName": "jiaotong",
            "bigImgName" : "jiaot_bank",
            "smallIcon" : 'jiaotong',
    	},
    	"CIB": {
    		"bankCode": "CIB",
    		"bankId": "66",
    		"bankName": "兴业银行",
    		"imgName": "xingye",
            "bigImgName" : "xingy_bank",
            "smallIcon" : 'xingye',
    	},
    	"CNCB": {
    		"bankCode": "CNCB",
    		"bankId": "67",
    		"bankName": "中信银行",
    		"imgName": "zhongxin",
            "bigImgName" : "zhongx_bank",
            "smallIcon" : 'zhongxin',
    	},
    	"CEB": {
    		"bankCode": "CEB",
    		"bankId": "68",
    		"bankName": "中国光大银行",
    		"imgName": "guangda",
            "bigImgName" : "guangd_bank",
            "smallIcon" : 'guangda',
    	},
    	"PAB": {
    		"bankCode": "PAB",
    		"bankId": "69",
    		"bankName": "平安银行",
    		"imgName": "pingan",
            "bigImgName" : "pinga_bank",
            "smallIcon" : 'pingan',
    	},
    	"PSBC": {
    		"bankCode": "PSBC",
    		"bankId": "70",
    		"bankName": "中国邮政储蓄银行",
    		"imgName": "youzheng",
            "bigImgName" : "youz_bank",
            "smallIcon" : 'youzheng',
    	},
    	"BOS": {
    		"bankCode": "BOS",
    		"bankId": "71",
    		"bankName": "上海银行",
    		"imgName": "shanghai",
            "bigImgName" : "shangh_bank",
            "smallIcon" : 'shanghai',
    	},
    	"SPDB": {
    		"bankCode": "SPDB",
    		"bankId": "72",
    		"bankName": "浦东发展银行",
    		"imgName": "pufa",
            "bigImgName" : "puf_bank",
            "smallIcon" : 'pufa',
    	},
    	"CMBC": {
    		"bankCode": "CMBC",
    		"bankId": "73",
    		"bankName": "中国民生银行",
    		"imgName": "minsheng",
            "bigImgName" : "mins_bank",
            "smallIcon" : 'minsheng',
    	},
    	"CMB": {
    		"bankCode": "CMB",
    		"bankId": "74",
    		"bankName": "招商银行",
    		"imgName": "zhaoshang",
            "bigImgName" : "zhaos_bank",
            "smallIcon" : 'zhaoshang',
    	},
    	"GDB": {
    		"bankCode": "GDB",
    		"bankId": "75",
    		"bankName": "广发银行",
    		"imgName": "guangfa",
            "bigImgName" : "guangf_bank",
            "smallIcon" : 'gongshang',
    	},
        "HXB": {
    		"bankCode": "HXB",
    		"bankId": "238",
    		"bankName": "华夏银行",
    		"imgName": "huaxia",
            "bigImgName" : "huax_bank",
            "smallIcon" : 'huaxia',
    	},
        "BCCB": {
            "bankCode": "BCCB",
            "bankId": "707",
            "bankName": "北京银行",
            "imgName": "beijing",
            "bigImgName" : "beijing_bank",
            "smallIcon" : 'beijing',
        },
        "ZSBC" : {
        	"bankCode": "ZSBC",
        	"bankId": "30",
        	"bankName": "浙商银行",
            "imgName": "zhejiang",
            "bigImgName" : "zhejiang_bank",
            "smallIcon" : 'zhejiang',
        },
        "GZBC" : {
        	"bankCode": "GZBC",
        	"bankId": "47",
        	"bankName": "广州银行",
            "imgName": "guangzhou",
            "bigImgName" : "guangzhou_bank",
            "smallIcon" : 'guangzhou',
        },
        "BRCB" : {
        	"bankCode": "BRCB",
        	"bankId": "48",
        	"bankName": "北京农商银行",
            "imgName": "beijingnongshang",
            "bigImgName" : "beijingnongshang_bank",
            "smallIcon" : 'beijingnongshang',
        },
        "JSBC" : {
        	"bankCode": "JSBC",
        	"bankId": "49",
        	"bankName": "江苏银行",
            "imgName": "jiangsu",
            "bigImgName" : "jiangsu_bank",
            "smallIcon" : 'jiangsu',
        },
        "HZBANK" : {
        	"bankCode": "HZBANK",
        	"bankId": "50",
        	"bankName": "杭州银行",
            "imgName": "hangzhou",
            "bigImgName" : "hangzhou_bank",
            "smallIcon" : 'hangzhou',
        },
        "BGZC" : {
        	"bankCode": "BGZC",
        	"bankId": "51",
        	"bankName": "贵州银行",
            "imgName": "guizhou",
            "bigImgName" : "guizhou_bank",
            "smallIcon" : 'guizhou',
        },
        "NBBC" : {
        	"bankCode": "NBBC",
        	"bankId": "51",
        	"bankName": "宁波银行",
            "imgName": "ningbo",
            "bigImgName" : "ningbo_bank",
            "smallIcon" : 'ningbo',
        },
        "EBCL" : {
        	"bankCode": "EBCL",
        	"bankId": "51",
        	"bankName": "恒丰银行",
            "imgName": "hengfeng",
            "bigImgName" : "hengfeng_bank",
            "smallIcon" : 'hengfeng',
        }
    }

    return bank[bankCode] ? bank[bankCode] : '';
}
export default {
    bankTrans
};
